# Generated by Django 4.0.2 on 2024-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodHandsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(verbose_name='Data odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(verbose_name='Czas odbioru'),
        ),
    ]
