# Generated by Django 4.0.2 on 2024-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodHandsApp', '0003_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.FloatField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1),
        ),
    ]
