# Generated by Django 4.0.2 on 2024-01-16 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodHandsApp', '0004_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='GoodHandsApp.Category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.FloatField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1, verbose_name='Instytucja'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=255, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateTimeField(verbose_name='Data odbioru')),
                ('pick_up_time', models.DateTimeField(verbose_name='Czas odbioru')),
                ('pick_up_comment', models.TextField(verbose_name='Komentarz do odbioru')),
                ('categories', models.ManyToManyField(to='GoodHandsApp.Category', verbose_name='Kategoria')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodHandsApp.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Darczyńca')),
            ],
        ),
    ]
